-- Add AI meal plan column to athlete_constraints
-- This stores the weekly meal plan generated by AI

ALTER TABLE athlete_constraints 
ADD COLUMN IF NOT EXISTS ai_meal_plan JSONB DEFAULT NULL;

ALTER TABLE athlete_constraints 
ADD COLUMN IF NOT EXISTS ai_meal_plan_updated_at TIMESTAMPTZ DEFAULT NULL;

-- Add index for faster queries
CREATE INDEX IF NOT EXISTS idx_athlete_constraints_ai_meal_plan 
ON athlete_constraints USING GIN (ai_meal_plan) 
WHERE ai_meal_plan IS NOT NULL;

COMMENT ON COLUMN athlete_constraints.ai_meal_plan IS 'AI-generated weekly meal plan with meals per day';
COMMENT ON COLUMN athlete_constraints.ai_meal_plan_updated_at IS 'When the AI meal plan was last updated';
